###############################################################
#  Generated by:      YONG-SHENG LIU (David)
#  Generated date:    2023/12/7
#  Design:            
#  Command:           information found in /usr/cad/CBDK/CBDK018_UMC_Faraday_v1.0/orig_lib/fsa0m_a/2009Q2v2.0/GENERIC_CORE/FrontEnd/synopsys/fsa0m_a_generic_core_ss1p62v125c.lib
###############################################################
set_parasitic_parameters -early_spec rcmax -late_spec rcmax
set_temperature 125
set_process_number 1
set_voltage 1.62 -object_list VDD
#set_voltage 3.0 -object_list [get_lib_cells P*]
#set_operating_conditions -library io_worst
set_timing_derate -early 0.95 -cell_delay -net_delay