###############################################################
#  Generated by:      YONG-SHENG LIU (David)
#  Generated date:    2023/12/7
#  Design:            
#  Command:           information found in /usr/cad/CBDK/CBDK018_UMC_Faraday_v1.0/orig_lib/fsa0m_a/2009Q2v2.0/GENERIC_CORE/FrontEnd/synopsys/fsa0m_a_generic_core_ff1p98vm40c.lib
###############################################################
set_parasitic_parameters -early_spec rcmin -late_spec rcmin
set_temperature -40
set_process_number 1
set_voltage 1.98 -object_list VDD
#set_voltage 3.6 -object_list [get_lib_cells P*]
set_operating_conditions -library io_best
set_timing_derate -late 1.05 -cell_delay -net_delay